import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { ScreenBackground } from '../components/ScreenBackground';
import { TopBar } from '../components/TopBar';
import { useTheme } from 'react-native-paper';
import { LIGHT_THEME, DARK_THEME } from '../theme/colors';
import type { RootStackScreenProps } from '../types/navigation';

export function TermsConditionsScreen({ navigation }: RootStackScreenProps<'TermsConditions'>) {
    const theme = useTheme();
    const TOKENS = theme.dark ? DARK_THEME : LIGHT_THEME;

    return (
        <ScreenBackground>
            <TopBar title="Terms & Conditions" />
            <ScrollView contentContainerStyle={styles.content}>
                <Text style={[styles.heading, { color: TOKENS.textPrimary }]}>Terms & Conditions</Text>
                <Text style={[styles.body, { color: TOKENS.textSecondary }]}>By using ManaStudy AI, you agree to our usage terms, including acceptable content and upload policies.</Text>

                <View style={[styles.card, { backgroundColor: TOKENS.surfaceAlt, borderColor: TOKENS.border }]}>
                    <Text style={[styles.cardTitle, { color: TOKENS.textPrimary }]}>Allowed documents</Text>
                    <Text style={[styles.cardText, { color: TOKENS.textSecondary }]}>You may upload PDFs, DOCX, PPTX, and common image formats. Do not upload copyrighted content without permission.</Text>
                </View>

                <View style={[styles.card, { backgroundColor: TOKENS.surfaceAlt, borderColor: TOKENS.border }]}>
                    <Text style={[styles.cardTitle, { color: TOKENS.textPrimary }]}>Service use</Text>
                    <Text style={[styles.cardText, { color: TOKENS.textSecondary }]}>Summaries are generated by Gemini and may not be perfect. Use outputs as study assistance, not legal or medical advice.</Text>
                </View>
            </ScrollView>
        </ScreenBackground>
    );
}

const styles = StyleSheet.create({
    content: {
        padding: 16,
        paddingBottom: 120,
    },
    heading: {
        fontSize: 28,
        fontWeight: '800',
        marginBottom: 10,
    },
    body: {
        fontSize: 14,
        marginBottom: 18,
        lineHeight: 22,
    },
    card: {
        borderWidth: 1,
        borderRadius: 16,
        padding: 16,
        marginBottom: 14,
    },
    cardTitle: {
        fontSize: 16,
        fontWeight: '700',
        marginBottom: 8,
    },
    cardText: {
        fontSize: 14,
        lineHeight: 20,
    },
});
